.gitignore, code/censo_escolar/colunas_constants.R, code/censo_escolar/export_censo_escolar.R, code/censo_escolar/fetch_censo_escolar_inep.R, data/censo_escolar/censo_escolar_2018.csv
- Adiciona módulo com funções para capturar e tratar dados do censo escolar de 2018. [Fonte](http://portal.inep.gov.br/censo-escolar) e [dados](http://portal.inep.gov.br/resultados-e-resumos)
- Adiciona csv com dados do censo escolar para os municípios do Rio Grande do Sul
- O script export_censo_escolar.R cria o csv com os dados do RS.
=> Adiciona dados do censo escolar em 2018

code/contratos/processa_alteracoes_contratos.R, code/utils/join_utils.R, code/utils/utils.R, feed/manage.py, feed/scripts/create_alteracoes_contrato.sql, feed/scripts/create_contrato.sql, feed/scripts/create_item.sql, feed/scripts/create_item_contrato.sql, feed/scripts/create_licitacao.sql, feed/scripts/update/update_alteracoes_contrato.sql, feed/scripts/update/update_contrato.sql, feed/scripts/update/update_item.sql, feed/scripts/update/update_item_contrato.sql, feed/scripts/update/update_licitacao.sql, feed/scripts/update/update_licitante.sql, feed/scripts/update/update_orgao.sql
- Cria scripts para atualização das tabelas no banco de dados
- Modifica critério de join para incluir apenas itens, alterações, contratos e afins que estejam nas duas tabelas participantes do cruzamento.
- Modifica tipo de colunas para evitar erros no parsing das tabelas durante o processamento dos dados (de integer para numeric).
- Será necessário executar novamente o script de criação das tabelas.
`docker exec -it feed python3.6 /feed/manage.py create`
- Para executar a atualização basta executar
`docker exec -it feed python3.6 /feed/manage.py update-data`
=> Cria módulo para atualização das tabelas no banco de dados

Makefile, README.md, feed/manage.py, feed/scripts/import/import_data.sql, feed/scripts/import/import_data_processed.sql
- Adiciona mais funções ao Makefile
- Documenta fluxo de processamento de dados
=> Melhora documentação do repositório

code/novidades/processa_novidades.R, feed/scripts/create/create_tipo_novidade.sql, feed/scripts/update/update_tipo_novidade.sql
- Cria um novo atributo **texto_resumo** na tabela tipo_novidade para melhor descerver os eventos de uma licitação
=> Cria novo atributo para melhor descrição do tipo de novidade

feed/scripts/create/create_alteracoes_contrato.sql, feed/scripts/create/create_contrato.sql, feed/scripts/create/create_empenho.sql, feed/scripts/create/create_item.sql, feed/scripts/create/create_item_contrato.sql, feed/scripts/create/create_licitacao.sql, feed/scripts/create/create_licitante.sql, feed/scripts/create/create_novidade.sql
- Permite que as mudanças nas chaves estrangeiras sejam refletidas nas tabelas correspondentes.
=> Adiciona complemento de efeitos nas cláusulas das chaves estrangeiras

feed/scripts/import/import_data.sql
Adiciona mais um campo na MATERIALIZED VIEW para referenciar o contrato
P.S. Não vi como modificar uma VIEW. O procedimento é apagar e depois recriar com a nova definição.
=> Adiciona o id do contrato a VIEW para referenciá-lo facilmente

code/licitacoes/processa_tipos_modalidade_licitacoes.R, code/processor/export_dados_bd.R, code/utils/join_utils.R, feed/scripts/create/create_licitacao.sql, feed/scripts/update/update_licitacao.sql
- Adiciona coluna com informações do tipo de modalidade da licitação
Fonte: [TCE-RS](http://www1.tce.rs.gov.br/portal/page/portal/tcers/jurisdicionados/sistemas_controle_externo/licitacon/e-validador/manual/Apendice_B_1.4.xlsx)
=> Adiciona coluna com informações do tipo de modalidade da licitação

feed/scripts/import/import_data.sql
- Adiciona nome do município na view materializada de itens de contrato
=> Adiciona nome do município na view materializada de itens de contrato

code/processor/export_dados_bd.R, code/utils/licitacoes_falsos_positivos.csv
- Adiciona lista com casos de falsos positivos na classificação de licitações de merenda
=> Adiciona lista com' casos de falsos positivos na classificação de licitações de merenda

code/utils/join_utils.R, docker-compose.yml, feed/scripts/create/create_item_contrato.sql, feed/scripts/import/import_data.sql, reports/itens-similares-amostra/lib/README.md, reports/itens-similares-amostra/lib/export_itens_similares.R, reports/itens-similares-amostra/lib/functions.R
- Adiciona módulo para gerar csv de itens similares 
- Assume que o PR https://github.com/analytics-ufcg/ta-na-mesa-dados/pull/72 foi revisado e aprovado
=>  Adiciona módulo para gerar csv de itens similares 

code/licitacoes/processa_documentos_licitacao.R, code/licitacoes/processa_licitacoes.R, code/licitacoes/processa_tipos_documentos_licitacoes.R, code/processor/export_dados_bd.R, code/utils/constants.R, code/utils/join_utils.R, code/utils/read_utils.R, code/utils/tipos_documentos_licitacao.csv, feed/manage.py, feed/scripts/create/create_documento_licitacao.sql, feed/scripts/drop/drop_tables.sql, feed/scripts/import/import_data.sql
- Adiciona módulo de documentos das licitações
- Cria funções para recuperar e processar documentos de licitações
- Adiciona arquivo com o mapeamento entre os tipos de documento e suas descrições
- CSVs gerados com as mudanças: https://drive.google.com/drive/u/0/folders/1OV4K_kLEonVN6QFQAN2EuKY-nVCvZWlG
=> Adiciona módulo de documentos das licitações

feed/scripts/import/import_data.sql
- Adiciona coluna com a quantidade de itens do contrato à view materializada
- É preciso executar novamente a atualização dos dados no BD ou ainda executar diretamente o comando para criar a view no shell do Postgres.
=> Adiciona coluna com a quantidade de itens do contrato à view materializada

Makefile, README.md, code/contratos/processa_contratos.R, code/contratos/processa_itens_contrato.R, code/empenhos/processa_empenhos.R, code/filters/filter_covid.R, code/filters/filter_merenda.R, code/licitacoes/processa_itens_licitacao.R, code/licitacoes/processa_licitacoes.R, code/processor/export_dados_bd.R, code/utils/read_utils.R, feed/scripts/create/create_item_contrato.sql, feed/scripts/create/create_licitacao.sql, feed/scripts/import/import_data.sql, feed/scripts/update/update_licitacao.sql, update-data.sh
- Adiciona possibilidade de executar o processamento de dados de acordo com o assunto (covid ou merenda)
- Modifica processamento para capturar licitações relacionadas ao COVID-19 (marcação dada pelo TCE-RS)
- Modifica tipo da coluna do número da licitação 
-  Adiciona coluna com a quantidade de itens do contrato à view materializada
- Depende da revisão e aprovação do PR https://github.com/analytics-ufcg/ta-na-mesa-dados/pull/75
- Dados já processados para o assunto covid estão disponíveis aqui https://drive.google.com/drive/u/0/folders/1YnadTUP8czpXKZNX_4XVthJqCP-Gzlhl
=>  Adiciona possibilidade de executar o processamento de dados de acordo com o assunto (covid ou merenda)

code/contratos/processa_fornecedores.R, code/processor/export_dados_bd.R, feed/scripts/create/create_fornecedor.sql
- Adiciona o total de contratos que um fornecedor já participou (usando todos os contratos baixados do TCE)
- Adicionar a data do primeiro contrato do fornecedor (usando todos os contratos baixados do TCE)
=> Adiciona informações do fornecedor como o total de contratos já realizados e a data do primeiro contrato

code/contratos/processa_fornecedores.R, code/contratos/processa_itens_contrato.R, code/empenhos/processa_empenhos.R, code/licitacoes/processa_eventos_licitacoes.R, code/licitacoes/processa_itens_licitacao.R, code/processor/export_dados_bd.R, code/utils/join_utils.R, code/utils/read_utils.R, feed/scripts/create/create_empenho.sql, feed/scripts/create/create_fornecedor.sql
- Adiciona filtro para inclusão de itens de licitações encerradas
- Faz merge com versão atual da branch development
=> Adiciona filtro para inclusão de itens de licitações encerradas

code/contratos/processa_compras.R, code/licitacoes/processa_itens_licitacao.R, code/licitacoes/processa_licitantes.R, code/licitacoes/processa_lotes_licitacao.R, code/processor/export_dados_bd.R, code/processor/export_fornecedores_bd.R, code/utils/read_utils.R, code/utils/utils.R, feed/manage.py, feed/scripts/create/create_contrato.sql, feed/scripts/create/create_item_contrato.sql
- Adiciona lógica para definir as compras feitas sem contratos e seus respectivos fornecedores
- Adiciona módulo de processamento de lotes
- Atualiza módulo de processamento das informações dos fornecedores
=> Adiciona lógica para definir as compras feitas sem contratos e seus respectivos fornecedores

code/fetcher/DAO_Receita.R, code/fetcher/scripts/fetch_dados_receita.R, feed/manage.py, feed/scripts/create/create_dados_cadastrais.sql, feed/scripts/create/create_natureza_juridica.sql, feed/scripts/drop/drop_tables.sql, feed/scripts/import/import_data.sql
- Adiciona tabela com código da natureza jurídica
- Adiciona informação descritiva do porte da empresa
=> Adiciona tabela com código da natureza jurídica

feed/scripts/drop/drop_tables.sql, feed/scripts/import/import_data.sql
Necessário re-executar os scripts `sudo make feed-clean-data`, `sudo make feed-create ` e `sudo make feed-import-data`, nesta ordem.
Exemplo de teste:
`SELECT word 
FROM unique_lexeme
WHERE similarity(word, 'salsixa') > 0.3
ORDER BY word <-> 'salsixa'
LIMIT 1;`
=> View materializada com lexemas para sugestao por similaridade

Makefile, README.md, code/alertas/README.md, code/alertas/cnaes_desconsiderados_produtos.csv, code/alertas/processa_alertas_data.R, code/processor/export_alertas_bd.R, update-data.sh
- Cria arquivo com lista de cnaes para serem ignorados no cálculo do alerta para produto fora do ramo
- Atualiza documentação
- Atualiza makefile
=> Adiciona exclusão de cnaes específicos para geração de alertas

Makefile, feed/scripts/create/create_empenho.sql, transformer/adapter/estados/RS/empenhos/adaptador_empenhos_rs.R, transformer/processor/estados/RS/empenhos/export_empenhos_bd.R, update-data.sh
- Refatora módulo do processador de empenhos para o RS
=> Refatora módulo do processador de empenhos para o RS

fetcher/estados/PE/tce/DAO_TCE_PE.R, transformer/adapter/estados/PE/contratos/adaptador_contratos_pe.R, transformer/processor/export_dados_bd.R, transformer/utils/read_utils.R
- Atualiza adaptador de contratos para usar nova tabela de contratos revisada
- Atualiza read_contratos_pe
=> Atualiza adaptador de contratos para usar nova tabela de contratos revisada

docker-compose.yml, fetcher/estados/RS/tce/fetch_all_data.py, fetcher/estados/RS/tce/fetch_contratos.py, fetcher/estados/RS/tce/fetch_empenhos.py, fetcher/estados/RS/tce/fetch_licitacoes.py, fetcher/estados/RS/tce/utils.py
- Considera o caminho do tce-rs como default para salvar dados brutos do tce-rs
=> Altera parâmetro do caminho em arquivos do fetcher do RS

feed/scripts/import/import_data.sql, transformer/adapter/estados/RS/contratos/adaptador_compras_rs.R
- Altera critério de formação do número do contrato para compras no RS
- Adiciona informações do contrato e da licitação na view dos itens similares
=> Altera critério de formação do número do contrato para compras no RS

transformer/processor/geral/alertas/cnaes_desconsiderados_produtos.csv
- Atualiza lista de cnaes que geram alertas que são falsos positivos
=> Atualiza lista de cnaes que geram alertas que são falsos positivos

update-data.sh
- Adiciona comando para criar tabela de empenhos raw
=> Adiciona comando para criar tabela de empenhos raw

feed/manage.py, feed/scripts/create/create_municipio.sql, feed/scripts/create/create_orgao.sql, feed/scripts/drop/drop_tables.sql, feed/scripts/import/import_data.sql, transformer/processor/estados/PE/orgaos/processador_orgaos_pe.R, transformer/processor/export_dados_bd.R
- Adiciona migrations para importação da tabela de municípios
- Adiciona slug do município
=> Adiciona migrations para importação da tabela de municípios

azure/stop_azure_vm.sh, update-data.sh
- Adiciona comando que copia zip para pasta permanente de dados
- Remove interação na execução do comando docker que dealoca a VM
=> Adiciona comando que copia zip para pasta permanente de dados

update-data.sh
- Modifica lógica para nome do arquivo zip com os csvs processados
=> Modifica lógica para nome do arquivo zip com os csvs processados

.gitignore, Makefile, README.md, data/.gitignore, transformer/adapter/estados/PE/contratos/adaptador_contratos_pe.R, transformer/adapter/estados/PE/contratos/adaptador_itens_contratos_pe.R, transformer/adapter/estados/PE/licitacoes/adaptador_licitacoes_pe.R, transformer/adapter/estados/RS/contratos/adaptador_contratos_rs.R, transformer/processor/aggregator/aggregator_compras.R, transformer/processor/aggregator/aggregator_contratos.R, transformer/processor/aggregator/aggregator_documentos_licitacao.R, transformer/processor/aggregator/aggregator_fornecedores.R, transformer/processor/aggregator/aggregator_itens_contrato.R, transformer/processor/aggregator/aggregator_itens_licitacao.R, transformer/processor/aggregator/aggregator_licitacoes.R, transformer/processor/aggregator/aggregator_licitantes.R, transformer/processor/aggregator/aggregator_municipios.R, transformer/processor/aggregator/aggregator_orgaos.R, transformer/processor/estados/RS/orgaos/processador_orgaos_rs.R, transformer/processor/export_dados_bd.R, transformer/utils/join_utils.R, update-data.sh
- Adiciona scripts de agregação
- Refatora script exportados dos dados para chamar scripts de agregação
- Permite que apenas um estado seja processado
Objetivos da mudanças
- Facilitar a manutenção do repositório
- Melhorar legibilidade do arquivo de exportação
- Melhorar identificação de erros no processamento (ainda tem um caminho pela frente pra deixar isso ideal)
- Facilitar inserir novos estados/municipios
- Permitir a execução do processamento para um estado específico
=> Refatora agregador e script exportador dos dados

transformer/adapter/estados/Federal/licitacoes/adaptador_licitacoes_federal.R, transformer/processor/aggregator/aggregator_compras.R, transformer/utils/join_utils.R
- Aplica inner_join para processar apenas contratos/empenhos relacionados à licitações
- Melhora log dos joins
=> Processa apenas contratos/empenhos relacionados à licitações

docker-compose.yml, feed/scripts/create/create_item.sql, feed/scripts/create/create_item_contrato.sql, feed/scripts/create/create_itens_empenhos_raw_federais.sql, transformer/adapter/estados/RS/contratos/adaptador_compras_rs.R, transformer/adapter/estados/RS/contratos/adaptador_itens_contratos_rs.R, transformer/processor/aggregator/aggregator_compras.R, transformer/processor/aggregator/aggregator_itens_contrato.R, transformer/utils/bd_constants.R, transformer/utils/join_utils.R
- Revisa processamento de itens federais
- Atualiza configuração de variáveis de ambiente para o Rstudio
- Atualiza schema
=> Revisa processamento de itens federais

.github/workflows/tadepe.yml, Dockerfile, docker-compose.yml, tests/testthat/README.md, tests/testthat/test_example.R
- Cria teste de exemplo para o módulo de testes do repositório
=> Inicia módulo de testes

transformer/adapter/estados/Federal/contratos/adaptador_itens_compra_federal.R
- Altera cálculo na função de agregação
=> Ajusta cálculo do histórico de itens

transformer/utils/read/read_empenhos_federais.R, transformer/utils/read/read_itens_empenhos_federais.R
- Remove modalidades de aplicação
=> Remove modalidades de aplicação
